// sanity/schemaTypes/seo.js
export default {
  name: 'seo',
  title: 'SEO & Social',
  type: 'object',
  fieldsets: [
    { name: 'social', title: 'Social Media / Open Graph' },
    { name: 'advanced', title: 'Advanced Settings' },
  ],
  fields: [
    {
      name: 'seoTitle',
      title: 'SEO Title (Meta Title)',
      type: 'string',
      description: 'ชื่อเรื่องที่จะแสดงบน Google (ถ้าเว้นว่าง จะใช้ชื่อหลักของหน้าแทน)',
      validation: (Rule) => Rule.max(60).warning('ควรมีความยาวไม่เกิน 60 ตัวอักษร'),
    },
    {
      name: 'seoDescription',
      title: 'SEO Description (Meta Description)',
      type: 'text',
      description: 'คำอธิบายสั้นๆ ที่จะแสดงบน Google (ประมาณ 155-160 ตัวอักษร)',
      rows: 3,
      validation: (Rule) => Rule.required().error('กรุณาใส่ Meta Description สำหรับ SEO').max(160).warning('ควรมีความยาวไม่เกิน 160 ตัวอักษร'),
    },
    {
      name: 'ogTitle',
      title: 'Social Title (Open Graph)',
      type: 'string',
      description: 'ชื่อเรื่องที่จะแสดงตอนแชร์ลงโซเชียล (ถ้าเว้นว่าง จะใช้ SEO Title แทน)',
      fieldset: 'social',
      validation: (Rule) => Rule.max(60).warning('ควรมีความยาวไม่เกิน 60 ตัวอักษร'),
    },
    {
      name: 'ogDescription',
      title: 'Social Description (Open Graph)',
      type: 'text',
      description: 'คำอธิบายที่จะแสดงตอนแชร์ลงโซเชียล (ถ้าเว้นว่าง จะใช้ SEO Description แทน)',
      rows: 3,
      fieldset: 'social',
      validation: (Rule) => Rule.max(160).warning('ควรมีความยาวไม่เกิน 160 ตัวอักษร'),
    },
    {
      name: 'ogImage',
      title: 'Social Image (Open Graph)',
      type: 'image',
      description: 'รูปภาพที่จะแสดงตอนแชร์ (แนะนำขนาด 1200x630 pixels)',
      fieldset: 'social',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      description: '(ไม่จำเป็น) ใส่ URL หลักของหน้านี้ หากมีหลาย URL ที่เข้าถึงเนื้อหาเดียวกันได้',
      fieldset: 'advanced',
    },
    {
      name: 'noIndexPage',
      title: 'Hide this page from search engines (noindex)',
      type: 'boolean',
      description: 'ติ๊กถูกเพื่อบอก Google ไม่ให้เก็บหน้านี้ไปแสดงผล',
      fieldset: 'advanced',
      initialValue: false,
    },
    {
      name: 'noFollowLinks',
      title: 'Do not follow links on this page (nofollow)',
      type: 'boolean',
      description: 'ติ๊กถูกเพื่อบอก Google ไม่ให้คลิกตามลิงก์ในหน้านี้',
      fieldset: 'advanced',
      initialValue: false,
    },
  ],
}